CREATE TABLE PasswordResets (
  id INT IDENTITY PRIMARY KEY,
  user_id INT NOT NULL,
  token NVARCHAR(255) NOT NULL,
  expires_at DATETIMEOFFSET NOT NULL DEFAULT DATEADD(HOUR, 24, SYSDATETIMEOFFSET()),
);
