-- USERS (mock)
INSERT INTO Users (username, email, password_hash, activation_hash, activated_at)
VALUES
('greg', 'greg@example.com', 'hash1', 'a1', SYSDATETIMEOFFSET()),
('guest', 'guest@example.com', 'hash2', 'a2', SYSDATETIMEOFFSET());

-- PLAYLISTS (mock)
INSERT INTO Playlists (user_id, title, views, likes, shares, is_public)
VALUES
(1, 'Idle.fm Starter Mix', 150, 20, 5, 1),
(2, 'Guest Favorites', 70, 10, 2, 1);

-- VIDEOS
INSERT INTO Videos (youtube_key, title, created_at)
VALUES
('p3gKeFiHK_4', 'Summer Lofi Hip Hop Mix 📚 for Studying and Working', '2023-10-01T23:58:12'),
('rBQwfCP3Jwk', 'Neon Dreams: Synthwave Cityscapes Generated by AI', '2023-10-02T00:14:22'),
('vJpo5dW3Ze4', 'WoW Synthwave Beats to Chill To | Journey to BlizzCon', '2023-10-24T12:17:38'),
('f02mOEt11OQ', 'code-fi / lofi beats to code/relax to', '2023-10-23T13:03:31'),
('OZYstiT0tMo', 'Lofi Radio ~ Beats to Relax/Study ✍️ Positive Lofi Music', '2023-10-25T01:54:29');

-- GIFS
INSERT INTO Gifs (tenor_key, title, created_at)
VALUES
('KeDD0PrMX1gAAAAC', 'Jake Lofi GIF', '2023-10-06T02:50:47'),
('R2GfWbKJ5bsAAAAC', 'Rock Head Bang GIF', '2023-10-06T02:51:42'),
('lkui1pjofksAAAAC', 'Midnight Vibes Indian Lofi GIF', '2023-10-06T03:01:03'),
('GiO4XNKti44AAAAC', 'Retrowave Synthwave GIF', '2023-10-06T03:01:06'),
('OXkJIpuc5iYAAAAC', 'Taxes Diablo GIF', '2023-10-08T19:33:43');

-- PLAYLISTVIDEOS
INSERT INTO PlaylistVideos (playlist_id, video_id, gif_id, position)
VALUES
(1, 1, 1, 10),
(1, 2, 2, 20),
(1, 3, 3, 30),
(2, 4, 4, 10),
(2, 5, 5, 20);
