POST http://localhost:8080/auth/reset-password
Content-Type: application/json

{
  "uid": "1015",
  "token": "60da16fd24df3ddc48c6ad40960e325614ccc1916bcbfc143198dcc5bf91d53d",
  "newPassword": "newSecurePassword123"
}
