POST http://localhost:8080/auth/reset-password
Content-Type: application/json

{
  "token": "2461995c04b2daff08ed96ed9d92d463c9eeb3504ddad0982f48a4ec469fed5f",
  "newPassword": "newSecurePassword123"
}
