GET http://localhost:8080/users/test-auth
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAxNSwiZW1haWwiOiJhY3RpdmVAdXNlci5jb20iLCJpYXQiOjE3NjAzNTA1NDAsImV4cCI6MTc2MDk1NTM0MH0.SxSQPJaWgQ0ybPWUVH7GI16hWwustvAopUD1VcCURYY
