GET http://localhost:8080/users/profile
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhY3RpdmUzQHVzZXIuY29tIiwiaWF0IjoxNzYwMzYyMjQ1LCJleHAiOjE3NjA5NjcwNDV9.GuBwrsyzrd9JVlxcT6PEWHOTjKtqTopk2uwxRxD9rdY
