GET http://localhost:8080/auth/me
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhZG1pbkBpZGxlLmZtIiwiaWF0IjoxNzYwNDgwMjAxLCJleHAiOjE3NjEwODUwMDF9.sPeTcMdN3pRYHBOJwFJHlKFAs6iUlhX4p14GA9_82R8
